In [1]:
import pandas as pd

df1 = pd.read_excel("28672.xlsx", sheet_name='Sheet1')
df2 = pd.read_excel("7269.xlsx", sheet_name='Sheet1')
df3 = pd.read_excel("917.xlsx", sheet_name='Sheet1')

In [2]:
# 这里的代码都同“插值处理.ipynb”，只是为了将有效数据取出，并加上列的名称方便查看
df1 = df1[:430]
df3 = df3[:709]
columns1 = ["THz"] + ["8"]*10 + ["13"]*10 + ["14"]*10 + ["15"]*10 + ["16"]*10 + ["17"]*10 + ["18"]*10 + ["19"]*10 + ["20"]*10
columns2 = ["THz"] + ["1"]*10 + ["2"]*10 + ["3"]*10 + ["6"]*10 + ["7"]*10
columns3 = ["THz"] + ["4"]*10 + ["5"]*10 + ["9"]*10 + ["10"]*10 + ["11"]*10 + ["12"]*10
df1.columns = columns1
df2.columns = columns2
df3.columns = columns3

In [3]:
df1

,THz,8,8,8,8,8,8,8,8,8,...,20,20,20,20,20,20,20,20,20,20
0,0.28672,0.36798,0.36798,0.36647,0.36798,0.46638,0.36203,0.34806,0.36798,0.43976,...,0.88030,0.86100,0.87661,0.88030,1.32045,1.32045,1.25584,0.61595,0.61621,1.28673
1,0.30000,0.36009,0.36424,0.36352,0.36465,0.44765,0.36784,0.35645,0.3632,0.43622,...,0.87356,0.85871,0.87355,0.87356,1.31182,1.31182,1.25257,0.61196,0.61218,1.28333
2,0.31328,0.36465,0.36628,0.36343,0.36798,0.42622,0.37361,0.36468,0.36434,0.43611,...,0.86977,0.85640,0.87050,0.86977,1.30706,1.30706,1.24928,0.60897,0.60996,1.27989
3,0.32672,0.36798,0.36834,0.36756,0.36798,0.40644,0.37943,0.37282,0.36782,0.44107,...,0.86802,0.85405,0.86742,0.86802,1.30235,1.30235,1.24596,0.60740,0.60776,1.27639
4,0.34000,0.37069,0.37420,0.37128,0.37069,0.39166,0.38515,0.38069,0.37191,0.44554,...,0.86522,0.85169,0.86438,0.86522,1.29786,1.29786,1.24266,0.60563,0.60567,1.27288
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
425,5.95328,0.54747,0.54848,0.54743,0.54747,0.53674,0.49735,0.53383,0.5477,0.65692,...,0.18298,0.19317,0.19008,0.18298,0.27584,0.27583,0.25371,0.12805,0.12872,0.28484
426,5.96656,0.62236,0.61987,0.62254,0.62236,0.57694,0.49727,0.55355,0.62184,0.74705,...,0.17825,0.19101,0.18705,0.17825,0.26862,0.26862,0.25049,0.12481,0.12536,0.28163
427,5.98000,0.69519,0.68861,0.69493,0.69519,0.60468,0.49745,0.57646,0.69339,0.83392,...,0.17413,0.18881,0.18395,0.17413,0.26203,0.26203,0.24724,0.12190,0.12228,0.27836
428,5.99328,0.76084,0.75773,0.75956,0.76084,0.61819,0.49792,0.60216,0.75851,0.91147,...,0.17061,0.18660,0.18086,0.17061,0.25610,0.25610,0.24400,0.11938,0.11951,0.27507
429,6.00656,0.81717,0.81717,0.81785,0.81717,0.61797,0.4987,0.63105,0.81717,0.98142,...,0.16746,0.18436,0.17774,0.16746,0.25119,0.25119,0.24075,0.11724,0.11722,0.27174

In [4]:
df2

,THz,1,1,1,1,1,1,1,1,1,...,7,7,7,7,7,7,7,7,7,7
0,0.007629,0.730346,7.63251,5.77874,0.73035,0.73035,3.86332,7.23395,-1.62280,0.73035,...,0.714668,6.91546,0.71467,0.71467,5.48507,6.80342,-1.40431,0.71467,-11.58016,-8.15519
1,0.015259,5.207089,7.10915,11.15187,4.94761,5.20709,4.37826,7.75916,6.42348,5.01248,...,5.137647,6.94015,4.93090,5.13765,5.41449,7.57261,6.33676,4.98111,-0.77498,8.56645
2,0.022888,8.905381,6.63559,14.09222,8.30606,8.90538,5.03519,7.86599,11.82080,8.69780,...,8.934486,6.94166,8.41439,8.93449,5.54805,7.95498,11.60798,8.87247,9.18301,9.55542
3,0.030518,11.773360,6.21183,13.92353,10.78522,11.77336,5.85410,7.56793,14.38964,11.84155,...,12.483260,6.91999,11.04072,12.48326,5.91770,7.96734,14.25614,12.14090,15.26657,10.94580
4,0.038147,14.914100,5.83788,10.75217,4.11850,8.90538,6.85232,6.97085,14.11265,14.58153,...,14.662590,6.87514,6.67150,8.93449,6.54980,7.71206,14.27274,14.62406,15.86698,16.18125
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1043,7.965088,-16.619680,-10.09624,-13.67497,-4.29490,-2.38553,-3.78715,-7.52399,-15.89808,-14.00795,...,-9.002760,-6.85060,-11.16478,-9.00276,-11.81573,-11.36060,-7.35796,-6.68849,-10.70364,-5.15708
1044,7.972717,-20.406900,-9.62705,-14.69169,-8.81213,-8.55413,-3.66872,-6.92528,-14.39523,-16.49690,...,-15.243430,-12.26735,-17.21840,-15.24343,-12.36490,-16.84290,-12.51900,-11.71292,-17.48483,-9.53186
1045,7.980347,-8.554134,-7.66708,-12.36755,-8.02005,-8.55413,-3.50927,-6.12351,-10.34501,-8.41118,...,-7.362059,-19.62253,-21.42101,-15.24343,-12.88731,-22.35663,-19.70437,-16.63915,-22.62308,-16.97927
1046,7.987976,3.870465,-4.21633,-7.36875,-1.02456,1.61000,-3.29147,-4.92759,-3.51087,0.19920,...,-36.589040,-28.91614,-28.00620,-36.58904,-13.35117,-28.00152,-28.94497,-30.09060,-23.86320,-33.02224
1047,7.995605,1.609997,0.72519,-0.85780,1.61000,1.61000,-2.99585,-3.26909,6.13033,1.61000,...,-39.822270,-40.14819,-39.82227,-39.82227,-13.72123,-33.92871,-40.50386,-39.82227,-20.01382,-33.28266

In [5]:
df3

,THz,4,4,4,4,4,4,4,4,4,...,12,12,12,12,12,12,12,12,12,12
0,0.0917,16.6037,14.5181,13.7532,12.7719,18.64499,16.25848,13.48349,14.71365,-44.63421,...,-6.9771,-4.2187,-6.97710,-7.05155,-6.9771,-6.97710,-4.21870,-4.21870,-4.48356,-4.2187
1,0.1000,17.0103,16.1739,11.9931,13.1101,17.50670,15.63763,13.35862,14.42082,-7.87010,...,-6.7204,-4.8259,-7.73723,-7.56596,-6.9771,-7.48302,-4.40225,-4.26103,-4.31059,-4.2187
2,0.1083,18.0552,18.8897,13.1453,18.1000,16.50203,15.30838,13.19093,14.07333,18.05328,...,-9.5142,-3.7385,-4.98120,-6.53079,-6.7204,-6.64063,-3.59190,-3.25294,-3.69528,-3.7385
3,0.1167,15.8848,15.4193,15.0953,15.4061,15.63099,15.27075,12.98043,13.67116,30.11626,...,-0.8137,-2.0647,-2.95500,-3.65346,-0.8806,-3.00555,-2.32120,-2.05554,-2.50834,-2.0647
4,0.1250,14.0509,13.7552,11.6317,12.0420,14.89356,15.52474,12.72711,13.21433,29.78011,...,-0.8806,-1.4169,-1.69752,1.22725,-0.8137,0.14475,-0.78255,-0.35852,-0.78303,-1.4169
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
704,5.9590,-20.0564,-6.8289,-13.2030,5.4548,-24.47250,3.20358,-0.36771,10.54397,-0.91428,...,-21.3518,-43.8776,-44.91132,-27.80869,-23.0432,-31.00820,-48.47458,-61.84524,-44.05771,-58.1891
705,5.9673,-11.6980,45.1276,-0.7738,2.8223,-35.26734,-3.64783,-6.22492,5.53017,-1.14308,...,-67.6759,-61.9827,-21.66024,-48.41541,-21.3518,-44.93670,-56.50803,-47.86198,-58.64928,-44.1604
706,5.9757,-25.3854,-11.2433,-13.9804,1.8767,-44.75634,-19.39213,-14.02231,-4.08992,-12.29812,...,-23.0432,-58.1891,-18.38760,-26.82410,-21.3518,-24.08482,-52.36525,-52.99798,-50.43012,-58.1891
707,5.9840,-27.0376,-15.3295,-12.8178,-33.6757,-59.05721,-36.82706,-25.70909,-20.17922,-34.74511,...,17.4230,-31.1001,-0.97010,-9.28362,2.7099,3.62817,-47.55743,-53.04320,-53.81835,-58.1891
708,5.9923,7.5418,9.4779,28.9948,28.7546,-73.03295,-59.50285,-41.10221,-39.71367,-65.20109,...,2.7099,-69.8404,2.70990,16.69336,2.7099,2.70990,-69.84040,-69.84040,-59.77444,-69.8404

In [6]:
from sklearn.metrics import r2_score

# 选择观测数据和拟合数据
huahewu1_observed_data = df2.iloc[:, 1]  # 第二列是观测数据
huahewu1_fitted_data = df2.iloc[:, 10]    # 第十一列是拟合数据

# 计算R²值
huahewu1_rfang = r2_score(huahewu1_observed_data, huahewu1_fitted_data)

# 打印R²值
print(f"化合物1的R²值为: {huahewu1_rfang}")

化合物1的R²值为: 0.9655970404940464

In [9]:
# 选择观测数据和拟合数据
huahewu8_observed_data = df1.iloc[:, 1]
huahewu8_fitted_data = df1.iloc[:, 10]
huahewu13_observed_data = df1.iloc[:, 11]
huahewu13_fitted_data = df1.iloc[:, 20]
huahewu14_observed_data = df1.iloc[:, 21]
huahewu14_fitted_data = df1.iloc[:, 30]
huahewu15_observed_data = df1.iloc[:, 31]
huahewu15_fitted_data = df1.iloc[:, 40]
huahewu16_observed_data = df1.iloc[:, 41]
huahewu16_fitted_data = df1.iloc[:, 50]
huahewu17_observed_data = df1.iloc[:, 51]
huahewu17_fitted_data = df1.iloc[:, 60]
huahewu18_observed_data = df1.iloc[:, 61]
huahewu18_fitted_data = df1.iloc[:, 70]
huahewu19_observed_data = df1.iloc[:, 71]
huahewu19_fitted_data = df1.iloc[:, 80]
huahewu20_observed_data = df1.iloc[:, 81]
huahewu20_fitted_data = df1.iloc[:, 90]

huahewu2_observed_data = df2.iloc[:, 11]
huahewu2_fitted_data = df2.iloc[:, 20]
huahewu3_observed_data = df2.iloc[:, 21]
huahewu3_fitted_data = df2.iloc[:, 30]
huahewu6_observed_data = df2.iloc[:, 31]
huahewu6_fitted_data = df2.iloc[:, 40]
huahewu7_observed_data = df2.iloc[:, 41]
huahewu7_fitted_data = df2.iloc[:, 50]

huahewu4_observed_data = df3.iloc[:, 1]
huahewu4_fitted_data = df3.iloc[:, 10]
huahewu5_observed_data = df3.iloc[:, 11]
huahewu5_fitted_data = df3.iloc[:, 20]
huahewu9_observed_data = df3.iloc[:, 21]
huahewu9_fitted_data = df3.iloc[:, 30]
huahewu10_observed_data = df3.iloc[:, 31]
huahewu10_fitted_data = df3.iloc[:, 40]
huahewu11_observed_data = df3.iloc[:, 41]
huahewu11_fitted_data = df3.iloc[:, 50]
huahewu12_observed_data = df3.iloc[:, 51]
huahewu12_fitted_data = df3.iloc[:, 60]

# 计算R²值
huahewu8_rfang = r2_score(huahewu8_observed_data, huahewu8_fitted_data)
huahewu13_rfang = r2_score(huahewu13_observed_data, huahewu13_fitted_data)
huahewu14_rfang = r2_score(huahewu14_observed_data, huahewu14_fitted_data)
huahewu15_rfang = r2_score(huahewu15_observed_data, huahewu15_fitted_data)
huahewu16_rfang = r2_score(huahewu16_observed_data, huahewu16_fitted_data)
huahewu17_rfang = r2_score(huahewu17_observed_data, huahewu17_fitted_data)
huahewu18_rfang = r2_score(huahewu18_observed_data, huahewu18_fitted_data)
huahewu19_rfang = r2_score(huahewu19_observed_data, huahewu19_fitted_data)
huahewu20_rfang = r2_score(huahewu20_observed_data, huahewu20_fitted_data)

huahewu2_rfang = r2_score(huahewu2_observed_data, huahewu2_fitted_data)
huahewu3_rfang = r2_score(huahewu3_observed_data, huahewu3_fitted_data)
huahewu6_rfang = r2_score(huahewu6_observed_data, huahewu6_fitted_data)
huahewu7_rfang = r2_score(huahewu7_observed_data, huahewu7_fitted_data)

huahewu4_rfang = r2_score(huahewu4_observed_data, huahewu4_fitted_data)
huahewu5_rfang = r2_score(huahewu5_observed_data, huahewu5_fitted_data)
huahewu9_rfang = r2_score(huahewu9_observed_data, huahewu9_fitted_data)
huahewu10_rfang = r2_score(huahewu10_observed_data, huahewu10_fitted_data)
huahewu11_rfang = r2_score(huahewu11_observed_data, huahewu11_fitted_data)
huahewu12_rfang = r2_score(huahewu12_observed_data, huahewu12_fitted_data)

In [10]:
# 使用列表推导式将所有变量的值添加到列表中
r_squared_values = [globals()[f'huahewu{i}_rfang'] for i in range(1, 21)]

# 打印列表中的R²值
for i in range(20):
    print(f"化合物{i + 1}的R²值为: {r_squared_values[i]}")

化合物1的R²值为: 0.9655970404940464
化合物2的R²值为: 0.9758956512683796
化合物3的R²值为: 0.9294884422673819
化合物4的R²值为: 0.839468188347128
化合物5的R²值为: 0.6815634955757697
化合物6的R²值为: 0.9660155473217732
化合物7的R²值为: 0.9776956543906227
化合物8的R²值为: 0.8034253131585802
化合物9的R²值为: 0.549522663732234
化合物10的R²值为: 0.8022787041209829
化合物11的R²值为: 0.6690368109521956
化合物12的R²值为: 0.811762525230616
化合物13的R²值为: 0.9999863972617182
化合物14的R²值为: 0.9999956092096522
化合物15的R²值为: 0.9979260066314758
化合物16的R²值为: 0.9631103000421333
化合物17的R²值为: 0.599424953790948
化合物18的R²值为: 0.6679776822513108
化合物19的R²值为: 0.8654107625707518
化合物20的R²值为: -0.9059684110264807

下面两个单纯是验证，和原始数据进行了比对

In [11]:
huahewu20_observed_data

0      0.88030
1      0.87356
2      0.86977
3      0.86802
4      0.86522
        ...
425    0.18298
426    0.17825
427    0.17413
428    0.17061
429    0.16746
Name: 20, Length: 430, dtype: float64

In [12]:
huahewu20_fitted_data

0      1.28673
1      1.28333
2      1.27989
3      1.27639
4      1.27288
        ...
425    0.28484
426    0.28163
427    0.27836
428    0.27507
429    0.27174
Name: 20, Length: 430, dtype: float64